### ISSUE TITLE
Powell Problem

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#67]
If I am missing sth. please let me know. But how come these problems are not caught as part of the integration test battery?

> `python estimation_reliability.py 
/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "estimation_reliability.py", line 61, in <module>
    estimate('test_intercepts.grmpy.ini', 'true_values')
  File "/home/peisenha/ownCloud/office/workspace/software/repositories/organizations/grmToolbox/grmpy/grmpy/estimate/estimate.py", line 40, in estimate
    minimizing_interface, x0, args=(dict_, data, rslt_dict), method=method, options=opts)
  File "/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 440, in minimize
    return _minimize_powell(fun, x0, args, callback, **options)
  File "/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 2471, in _minimize_powell
    direc[-1] = direc1
ValueError: setting an array element with a sequence.

[bug.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1362264/bug.grmpy.txt)
`

**Comment by peisenha** [comment]
Is this the same problem of #53? If so please think hard about how to add test to our test battery that allows us to detect the problem in the future/

**Comment by peisenha** [comment]
After some research online, let us go for the cheap way out. Remove the direc flag from the initialization dictionary and set it to its default value of None internally.

**Comment by SeBecker** [comment]
Done.
