### ISSUE TITLE
BIG II

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#80]
[test.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1390113/test.grmpy.txt)

Traceback (most recent call last):
  File "run.py", line 24, in <module>
    grmpy.estimate('test.grmpy.ini')
  File "../../grmpy/estimate/estimate.py", line 35, in estimate
    x0 = start_values(dict_, data, option)
  File "../../grmpy/estimate/estimate_auxiliary.py", line 71, in start_values
    init_dict['AUX']['init_values'][2 * numbers[0] + numbers[1] + 5])
ZeroDivisionError: float division by zero

**Comment by SeBecker** [comment]
see #79
